<?php

namespace AppBundle\Repository;

/**
 * ImporterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImporterRepository extends \Doctrine\ORM\EntityRepository
{
}
